// ============================================
// AUTO-GENERATED BY SYNAPSE - DO NOT EDIT
// ============================================
// iOS 17+ Compliant | Generated: TIMESTAMP
// Re-run `just gen-ui` to regenerate
//
// This file bridges Rust structs to SwiftUI ViewModels.
// The source of truth lives in Rust. This is just the interface.
// ============================================

import SwiftUI
import Foundation
import Observation

// Import your UniFFI-generated module here:
// import DriftCore

/// A reef location with vibe scoring
// MARK: - ReefViewModel (iOS 17+ @Observable)
@Observable
@MainActor
final class ReefViewModel {
    var lat: Double
    var lon: Double
    var vibe_score: Int
    var name: String
    var is_active: Bool

    init(
        lat: Double = 0.0,
        lon: Double = 0.0,
        vibe_score: Int = 0,
        name: String = "",
        is_active: Bool = false
    ) {
        self.lat = lat
        self.lon = lon
        self.vibe_score = vibe_score
        self.name = name
        self.is_active = is_active
    }
}

extension ReefViewModel {
    /// Create from UniFFI-bridged Rust struct
    static func from(rust: Reef) -> ReefViewModel {
        return ReefViewModel(
            lat: rust.lat,
            lon: rust.lon,
            vibe_score: rust.vibe_score,
            name: rust.name,
            is_active: rust.is_active
        )
    }
}

/// Player state for the Drift game
// MARK: - PlayerStateViewModel (iOS 17+ @Observable)
@Observable
@MainActor
final class PlayerStateViewModel {
    var coffee_count: Int
    var is_drifting: Bool
    var current_speed: Double
    var username: String

    init(
        coffee_count: Int = 0,
        is_drifting: Bool = false,
        current_speed: Double = 0.0,
        username: String = ""
    ) {
        self.coffee_count = coffee_count
        self.is_drifting = is_drifting
        self.current_speed = current_speed
        self.username = username
    }
}

extension PlayerStateViewModel {
    /// Create from UniFFI-bridged Rust struct
    static func from(rust: PlayerState) -> PlayerStateViewModel {
        return PlayerStateViewModel(
            coffee_count: rust.coffee_count,
            is_drifting: rust.is_drifting,
            current_speed: rust.current_speed,
            username: rust.username
        )
    }
}

/// GPS telemetry data
// MARK: - TelemetryViewModel (iOS 17+ @Observable)
@Observable
@MainActor
final class TelemetryViewModel {
    var latitude: Double
    var longitude: Double
    var altitude: Double
    var accuracy: Float
    var timestamp: Int64

    init(
        latitude: Double = 0.0,
        longitude: Double = 0.0,
        altitude: Double = 0.0,
        accuracy: Float = 0.0,
        timestamp: Int64 = 0
    ) {
        self.latitude = latitude
        self.longitude = longitude
        self.altitude = altitude
        self.accuracy = accuracy
        self.timestamp = timestamp
    }
}

extension TelemetryViewModel {
    /// Create from UniFFI-bridged Rust struct
    static func from(rust: Telemetry) -> TelemetryViewModel {
        return TelemetryViewModel(
            latitude: rust.latitude,
            longitude: rust.longitude,
            altitude: rust.altitude,
            accuracy: rust.accuracy,
            timestamp: rust.timestamp
        )
    }
}

/// User preferences (synced to iCloud)
// MARK: - UserPreferencesViewModel (iOS 17+ @Observable)
@Observable
@MainActor
final class UserPreferencesViewModel {
    var haptic_enabled: Bool
    var audio_cues_enabled: Bool
    var dark_mode: Bool
    var notification_radius: Double

    init(
        haptic_enabled: Bool = false,
        audio_cues_enabled: Bool = false,
        dark_mode: Bool = false,
        notification_radius: Double = 0.0
    ) {
        self.haptic_enabled = haptic_enabled
        self.audio_cues_enabled = audio_cues_enabled
        self.dark_mode = dark_mode
        self.notification_radius = notification_radius
    }
}

extension UserPreferencesViewModel {
    /// Create from UniFFI-bridged Rust struct
    static func from(rust: UserPreferences) -> UserPreferencesViewModel {
        return UserPreferencesViewModel(
            haptic_enabled: rust.haptic_enabled,
            audio_cues_enabled: rust.audio_cues_enabled,
            dark_mode: rust.dark_mode,
            notification_radius: rust.notification_radius
        )
    }
}

// MARK: - SwiftUI Previews

#if DEBUG
struct ReefViewModel_Previews: PreviewProvider {
    static var previews: some View {
        Text("Reef Preview")
            .environmentObject(ReefViewModel())
    }
}

struct PlayerStateViewModel_Previews: PreviewProvider {
    static var previews: some View {
        Text("PlayerState Preview")
            .environmentObject(PlayerStateViewModel())
    }
}

struct TelemetryViewModel_Previews: PreviewProvider {
    static var previews: some View {
        Text("Telemetry Preview")
            .environmentObject(TelemetryViewModel())
    }
}

struct UserPreferencesViewModel_Previews: PreviewProvider {
    static var previews: some View {
        Text("UserPreferences Preview")
            .environmentObject(UserPreferencesViewModel())
    }
}

#endif
